name: barberapp
description: App de gestão e agendamento para barbearias (Flutter + Supabase + Asaas).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1   # gerência de estado
  go_router: ^14.0.0         # navegação
  supabase_flutter: ^2.5.0   # backend (auth, db, realtime, storage)
  intl: ^0.19.0              # datas/moeda

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
